site_name: Athena @ IBM TechXchange 2024
copyright: Copyright &copy; 2024 Athena Decision Systems
repo_url: https://github.com/AthenaDecisionSystems/athena-ibm-techchange
nav:
  - Introduction: index.md

theme: 
  name: material
  logo: assets/OWL.png
  favicon: assets/OWL.png
  palette:
    scheme: default
  language: en
  features:
      - content.code.annotate
      - content.code.copy
      - content.tooltips
      - search.highlight
      - navigation.instant
      - navigation.instant.progress
      - navigation.tabs
      - navigation.tabs.sticky
      - navigation.instant
      - navigation.tracking
      - navigation.top
      - navigation.footer
extra_css: ["extra.css"]
plugins:
  - search:
      lang: en
  - minify:
      minify_html: true
  - mkdocs-video:
      is_video: True
      video_muted: True
      video_controls: True
      css_style:
        width: "75%"
markdown_extensions:
  - abbr
  - attr_list
  - md_in_html
  - admonition
  - codehilite
  - footnotes
  - tables
  - pymdownx.smartsymbols
  - toc:
      permalink: true
      toc_depth: 3
  - pymdownx.tabbed
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.details
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

extra:
  social:
    - icon: fontawesome/brands/github
      link: 'https://github.com/AthenaDecisionSystems'
    - icon: fontawesome/brands/linkedin
      link: 'https://www.linkedin.com/company/athena-decision-systems/'